### PR TITLE
Edited grapher lines to align with the x and y axes

### PR DESCRIPTION
**Pull request by Valenciola**
If you check the image below, you can see that I've edited the `draw.js` of the grapher folder to make the graph lines align with the axes.

Screenshot (24)

Check it out and merge it if you think it looks okay.

### CODE REVIEW

**Comment by AlexanderJCS** [comment]
Hi Valerie,

It looks like either the grid lines + the x-y axis or the graph line is 1 pixel lower than it should be. Take a look at this screenshot.

image

However, I really don't think the 1-pixel difference is that important. Realistically nobody is going to count the pixels.

If you want to fix it, go ahead. Otherwise feel free to merge this PR yourself.

**Comment by AlexanderJCS** [comment]
Using some basic Photoshop skills, this is what the line should look like. Very slight difference
image

**Comment by AlexanderJCS** [comment]
Update: it seems that the graph passes through (0, 0) perfectly so it's probably the gridlines that are at fault.

image

**Comment by Valenciola** [comment]
I just took a look and it seems like your 1-pixel observation was spot-on (and if it wasn't, it was definitely very close). Of course, I haven't zoomed in *super* close but I think this should fix the slight difference. Let me know if it doesn't and I'll start experimenting with different values.

Screenshot (26)

On a separate note (you all are gonna *love* this), it appears like each grid intersection is representing 0.5 instead of 1. I'm not super sure how this would be fixed if we do try to fix it... but let's go one issue at a time.

**Comment by AlexanderJCS** [comment]
You're gonna *love* this: now it appears to be one pixel too much, in the opposite direction !!!

image

**Comment by Valenciola** [comment]
Intermediate values of 0.5 it is! Also, is there a program you used to zoom in so close? Maybe I can test it myself before sending it over.

**Comment by AlexanderJCS** [comment]
I just take a screenshot and use an image editor (MS paint, photoshop, etc).

Personally I use paint.net (.net refers to the .NET framework it uses, *not* their website. You install it at https://www.getpaint.net). A few things to note if you want this program in particular:
1. It's basically a free, lightweight, but less feature-complete version of photoshop
2. Yes, their website looks sketch. No, it's not a virus (honestly don't know why they can't just hire a front end UI person or something, their website has looked like this for over a decade)
3. The Microsoft Store version is paid but includes an auto-updater

**Comment by Valenciola** [comment]
@AlexanderJCS I just adjusted the x and y values and I tried to look at it as closely as I could with screenshots (I had to borrow a Mac to do it really quick). Take a look and let me know how close I am.

Screen Shot 2024-03-02 at 11 06 55 PM

Honestly at this point if it's still not completely aligned I'm gonna try to address the hotkey issue and then come back to this, since it won't be super noticeable when we record to demo video for it. Plus, it might be a plus to talk about the hotkeys a little bit in the video if we decide to do that. Just let me know!

**Comment by AlexanderJCS** [comment]
Yes!!!! I double-checked, this is perfectly aligned!

Merging now, thanks for fixing this!

**Pull request merged**
