### PR TITLE
Fix node deletion & dragging cancellation

### LINKED ISSUE #3: Nodule connections remain after node block is deleted
When connecting two node blocks, the connections update, causing a line to be drawn between the two nodules.
image
Upon deleting the connected nodule, however, the line is still connected to where the nodule would have been. This is most possibly due to the fact that the nodule objects are still contained within the object it is connected to, despite the fact that the parent object (the node) has been deleted. 
image
However, the contents of the object are not modified, even when the screen is updated, allowing the user to drag around a node block connected to a nonexistent nodule.
image

### PR DESCRIPTION
**Pull request by AlexanderJCS**
Two polish changes:
1. Fixes #3 - when deleting a node block, the connections to the node block will also delete
2. When cancelling dragging a nodule, the "preview connection" now also disappears. To replicate the issue that this PR fixes, select a nodule, drag it, then, without connecting to another nodule, let go of left click. The connector will remain until the left mouse button is clicked.

### CODE REVIEW

**Comment by Valenciola** [comment]
WAIT YOU FIXED THE HANGING LINE DELETION ISSUE???

**Comment by AlexanderJCS** [comment]
Found a critical flaw. Turns out the connection of nodes is dependent on the hanging deletion issue. DO NOT MERGE THIS BRANCH UNTIL I SAY SO

**Comment by AlexanderJCS** [comment]
> WAIT YOU FIXED THE HANGING LINE DELETION ISSUE???

Yeah, it was pretty simple. The code was already added, but it would always error out before the graph could be re-rendered.

**Comment by Valenciola** [comment]
I CAN'T BELIEVE IT THIS IS AWESOME

**Comment by AlexanderJCS** [comment]
Fixed the issue. Turns out it was just an if statement being dumb. You guys are free to merge once you verified the code

**Pull request merged**
